# Define Portability Tune Arguments: devices, inputs, arguments, # of kernels, and tuning metric
devices:
   - [Intel(R) Gen9 HD Graphics NEO, 750]
   - [Intel(R) Gen9 HD Graphics NEO, 1150]
   - [Quadro P5000, 1733]
   - [Mali-G71, 5]
   - [Radeon RX Vega, 1630]
inputs:
- [256, 256, 256]
- [256, 256, 512]
- [256, 256, 1024]
- [256, 256, 4096]
- [256, 512, 256]
- [256, 512, 512]
- [256, 512, 1024]
- [256, 512, 4096]
- [256, 1024, 256]
- [256, 1024, 512]
- [256, 1024, 1024]
- [256, 1024, 4096]
- [256, 4096, 256]
- [256, 4096, 512]
- [256, 4096, 1024]
- [256, 4096, 4096]
- [512, 256, 256]
- [512, 256, 512]
- [512, 256, 1024]
- [512, 256, 4096]
- [512, 512, 256]
- [512, 512, 512]
- [512, 512, 1024]
- [512, 512, 4096]
- [512, 1024, 256]
- [512, 1024, 512]
- [512, 1024, 1024]
- [512, 1024, 4096]
- [512, 4096, 256]
- [512, 4096, 512]
- [512, 4096, 1024]
- [512, 4096, 4096]
- [1024, 256, 256]
- [1024, 256, 512]
- [1024, 256, 1024]
- [1024, 256, 4096]
- [1024, 512, 256]
- [1024, 512, 512]
- [1024, 512, 1024]
- [1024, 512, 4096]
- [1024, 1024, 256]
- [1024, 1024, 512]
- [1024, 1024, 1024]
- [1024, 1024, 4096]
- [1024, 4096, 256]
- [1024, 4096, 512]
- [1024, 4096, 1024]
- [1024, 4096, 4096]
- [4096, 256, 256]
- [4096, 256, 512]
- [4096, 256, 1024]
- [4096, 256, 4096]
- [4096, 512, 256]
- [4096, 512, 512]
- [4096, 512, 1024]
- [4096, 512, 4096]
- [4096, 1024, 256]
- [4096, 1024, 512]
- [4096, 1024, 1024]
- [4096, 1024, 4096]
- [4096, 4096, 256]
- [4096, 4096, 512]
- [4096, 4096, 1024]
- [4096, 4096, 4096]
# use the devices below for the clblast dataset, and only with m=n=k=1024
db_devices:
- [AMD Radeon RX590 GME, 1366]
- [NVIDIA GeForce RTX 2070 Super, 1380]
- [NVIDIA GeForce RTX 4070 Laptop GPU, 1605]
- [Apple M1, 1000]
- [AMD FirePro W8100, 824]
- [AMD Radeon VII, 1801]
- [GeForce GTX 1070 Ti, 1683]
- [Tesla P4, 1113]
- [NVIDIA GeForce RTX 4060, 2475]
- [NVIDIA GeForce RTX 4080, 2535]
- [AMD Radeon RX 6800 XT, 2575]
  # - [Radeon RX Vega, 1630]
- [TITAN RTX, 1770]
- [AMD Radeon Pro 580 Compute Engine, 1200]
- [PowerVR B-Series BXE-4-32, 594]
- [Intel(R) Iris(R) Xe Graphics, 1300]
- [NVIDIA GeForce GT 730, 901]
- [Apple M2 Max, 1000]
- [AMD Radeon RX 580 2048SP, 1284]
- [GeForce GTX 580, 1566]
- [GeForce 920MX, 993]
- [Quadro GV100, 1627]
- [NVIDIA GeForce RTX 3050 Ti Laptop GPU, 1695]
- [NVIDIA GeForce RTX 3080, 1710]
- [Intel(R) HD Graphics 6000 BroadWell U-Processor GT3, 1000]
- [AMD Radeon(TM) Graphics, 2000]
- [Radeon RX 7900 XTX, 3220]
- [NVIDIA GeForce GTX 1650 SUPER, 1725]
- [Intel(R) HD Graphics 620, 1000]
- [Mali-T760, 200]
- [Tesla P100-PCIE-16GB, 1328]
- [NVIDIA GeForce RTX 3090, 1695]
- [AMD Radeon RX 6600 XT, 2900]
- [A100-PCIE-40GB, 1410]
- [NVIDIA GeForce RTX 3080 Ti, 1665]
- [GeForce GTX 760 Ti OEM, 980]
- [NVIDIA GeForce MX150, 1531]
- [AMD Radeon Graphics, 2200]
- [AMD Radeon RX 7800 XT, 2254]
- [Quadro T2000, 1620]
- [Mali-T628, 543]
- [Intel(R) Arc(TM) A770 Graphics, 2400]
- [NVIDIA GeForce RTX 3080 Laptop GPU, 1365]
- [GeForce GTX 1080 Ti, 1620]
- [NVIDIA GeForce RTX 3070, 1725]
- [AMD Radeon RX 7600, 2356]
- [Intel(R) HD Graphics Skylake ULT GT2, 1000]
- [AMD Radeon RX 5700, 1625]
- [NVIDIA GeForce RTX 4060 Ti, 2595]
- [NVIDIA GeForce RTX 2070 with Max-Q Design, 1125]
- [NVIDIA GeForce RTX 2080 with Max-Q Design, 1095]
- [GeForce GTX 970, 1253]
- [GeForce GTX 1650, 1560]
- [NVIDIA GeForce RTX 3070 Ti Laptop GPU, 1410]
- [AMD Radeon RX 5700 XT, 2100]
- [AMD Radeon(TM) Graphics, 1600]
- [AMD Radeon 500 Series, 1046]
- [NVIDIA GeForce RTX 2070 SUPER, 1815]
- [AMD Radeon RX 6900 XT, 2015]
- [Intel(R) UHD Graphics 770, 1650]
- [GeForce 920A, 954]
- [Intel(R) RaptorLake-S Mobile Graphics Controller, 1650]
- [Intel(R) UHD Graphics 620, 1150]
- [AMD Radeon(TM) RX Vega 10 Graphics , 1400]
- [NVIDIA GeForce RTX 2080 Ti, 1545]
- [Tesla V100-PCIE-16GB, 1380]
- [Tesla T4, 1620]
- [NVIDIA GeForce RTX 4090, 2520]
- [NVIDIA GeForce GTX 1060 6GB, 1708]
- [AMD Radeon Pro 450 Compute Engine, 300]
- [NVIDIA GeForce RTX 4070 Ti, 2610]
- [AMD Radeon RX 6700 XT, 2855]
- [AMD Radeon RX 6500 XT, 2610]

# other arguments
arguments: [[arg_alpha, [2]], [arg_beta, [2]], [precision, [32]]] # keep this, it prunes out results from any other alpha/beta/precisions just in case
kernel: xgemm
num_kernels: [50] # the number of variants we are choosing (more = better performance, less = more utilization of perfport)
tuning_metric: geomean # the summarization metric for runtimes 
dummy_metric: dummy # holdover code

# Define Baseline (used for graphs that compare to CLBlast default behavior)
baseline_inputs: [ [1024, 1024, 1024 ] ]
baseline_arguments: []

# Define Tuner Configuration
tuning_time: 30
database_path: ../datasets/database_means.json
clblast_database_path: ../datasets/clblast_database_new_pruned.json
# for jwlawson-format csv files (one is already provided in ../datasets/xgemm.csv)
data_files:
- "../datasets/xgemm.csv"
oracle_adjust: True # should runtimes be normalized relative to minimum runtime?
minimum_coverage: 0.91 # the minumum number of device-input combinations a set of variants must cover to be considered
parallel_evals: 8 # doesn't seem to effect anything...

# Define Output
graph_types: [boxplot] # ipscatter
graph_titles: [device portable graph]
graph_labels: [geomean slowdown]
